# Generated by Django 4.1.2 on 2022-11-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_remove_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expend", models.IntegerField()),
                ("memo", models.TextField()),
                ("is_deleted", models.CharField(default="V", max_length=1)),
                ("deleted_at", models.DateTimeField()),
                ("recovered_at", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
    ]
