databases:
  host: "localhost"
  port: 3306
  database: "account_book"
  username: ""
  password: ""
  timezone: "+09:00"

secrets:
  django: ""

token:
  scret: ""
  referesh_expire_day: 7
  expire_sec: 3600